In [3]:
from sklearn.cluster import KMeans
import numpy as np

In [5]:
# Lets take the input points in form of array
X = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])

In [6]:
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [19]:
# create the Cluster models with 2 clusters

kmeans = KMeans(n_clusters=2, random_state=0)

In [20]:
# Fit the input data in the Kmeans Clusters

kmeans.fit(X)

KMeans(n_clusters=2, random_state=0)

In [22]:
# Checking the labels of the Kmeans clusters

kmeans.labels_

array([1, 1, 1, 0, 0, 0])

# There are 2 clusters 1 and 0
    First 3 points belongs to Clusters 1
    Next 3 points belongs to Clusters 0 

In [11]:
predict_point = np.array([[0,0],[12,3]])

In [12]:
kmeans.predict(predict_point)

array([1, 0])

# Prediction for the 2 points  
    Point1 (0,0) belongs to Clusters 1
    Point2 (12,3) belongs to Clusters 0

In [18]:
kmeans.cluster_centers_

array([[10.,  2.],
       [ 1.,  2.]])

# Cluster Centre or the Centroid
    Point(10,2) is the Centroid for Cluster 0
    Point(1,2) is the centroid of Clusters 1